extends Node

enum LANGUAGE {AMERICAN,}

#Mechanics Enums
enum DAMAGE_TYPE {NONE, PHYS, MAG, TRUE,}
enum TIME {NONE, DAY,NIGHT,}
enum CATEGORY {NONE, BLADE, KNIFE, BLUNT, NATURAL, STICK, GOHEI, BOOK, OFUDA, SCROLL, GUN, BOW, ACC, ITEM,}
#Skill Enums
#Enemy, Self, Ally, Self+(This is Self and Ally), Other(Enemy or Ally, not Self)

#Rule Types
enum RULE_TYPE{NONE, TIME, TARGET_SPEC, SELF_SPEC, MORPH,}
enum SUB_RULE{NONE, DAY, NIGHT}

#Effect Enums
enum EFFECT_TYPE {NONE, LIFE_STEAL, TIME, BUFF, DEBUFF, STATUS, DAMAGE, HEAL, COMP_HEAL, COMP_DMG, CURE, RELOC, ADD_SKILL, ADD_PASSIVE, MULTI_SWING, MULTI_ROUND, CRIT_BUFF, SLAYER,}
enum EFFECT_TARGET {NONE, SELF, TARGET, GLOBAL, EQUIPPED,}
enum TARGET_TEAM {NONE, ALLY, ENEMY,}
enum SKILL_TARGET {NONE, SELF, ALLY, ENEMY, MAP, SELF_ALLY}
enum SUB_TYPE {NONE, ALL, RANDOM, ACTED, SLEEP, MOVE, LIFE, COMP, PWR, MAG, ELEG, CELE, DEF, CHA, HIT, DMG, GRAZE, BARRIER, BARPRC, CRIT, LUCK, RESIST, EFFHIT, DRES, TOSS, SHOVE, WARP, DASH, SPEED_UP, SLOW_DOWN,}
enum STATUS_EFFECT {NONE, ALL, RANDOM, ACTED, SLEEP,}
enum DURATION_TYPE {NONE, TURN, ROUND, PERMANENT}

#Passive Enums
enum PASSIVE_TYPE {NONE, VANTAGE, STAT_CHANGE, AURA, RESPONSE, FATED, SUB_WEAPON, NIGHT_PROT, DAY_PROT, PASS,}

#Unit Enums
enum UNIT_ID {NONE, Remilia, Sakuya, Patchy, China,}
enum FACTION_ID {NONE, ENEMY, PLAYER, NPC,}
enum MOVE_TYPE {FOOT, RANGER, FLY, MOUNT, ARMOR} #Note to self, when combining role+spec compare move_type and pick which ever is higher
enum SPEC_ID {NONE,FAIRY,HUMAN,VAMPIRE,DRAGON,MAGICIAN,YOUKAI,ONI}
#, Human, Kappa, Lunarian, Oni, Doll, Devil, Yukionna, Zombie, Hermit, Magician, Spirit
enum ROLE_ID {NONE, TRBLR, THIEF,LADY, MAID, SORCERESS, MIKO, GUARD, WITCH,}
enum ACTION_TYPE {WEAPON, FRIENDLY_SKILL, HOSTILE_SKILL}


enum CORE_STAT {NONE, MOVE, LIFE, COMP, PWR, MAG, ELEG, CELE, DEF, CHA,}
enum ACTION_FAIL {NONE, DEAD, SLEEP, REACH, STRUCK}
enum WEAPON_CATEGORY {NONE, ANY, UNARMED, BLADE, BLUNT, STICK, BOW, GUN, GOHEI, BOOK, OFUDA, ACC, ITEM}
enum WEAPON_SUB {NONE, KNIFE, NATURAL}
#Combat Enums
enum COMP_TRIGGERS {NONE, ATTACK, WAS_HIT, MISS, DODGE, NEG_EFF, HEALED, MOVE, SKILL, CRIT, KILL, BREAK}
