extends Node

enum LANGUAGE {AMERICAN,}

#Mechanics Enums
enum DAMAGE_TYPE {NONE, PHYS, MAG, TRUE,}
enum TIME {NONE, DAY,NIGHT,}
#Skill Enums
#Enemy, Self, Ally, Self+(This is Self and Ally), Other(Enemy or Ally, not Self)

#Rule Types
enum RULE_TYPE{NONE, TIME, TARGET_SPEC, SELF_SPEC}
enum SUB_RULE{NONE, DAY, NIGHT}

#Effect Enums
enum EFFECT_TYPE {NONE, LIFE_STEAL, TIME, BUFF, DEBUFF, STATUS, DAMAGE, HEAL, COMP_HEAL, COMP_DMG, CURE, RELOC, ADD_SKILL, ADD_PASSIVE, MULTI_SWING, MULTI_ROUND, CRIT_BUFF, SLAYER,}
enum EFFECT_TARGET {NONE, SELF, TARGET, GLOBAL, EQUIPPED}
enum SUB_TYPE {NONE, ALL, RANDOM, ACTED, SLEEP, MOVE, LIFE, COMP, PWR, MAG, ELEG, CELE, BAR, CHA, HIT, DMG, AVOID, GRAZE, GRZPRC, CRIT, CRTAVD, RESIST, EFFHIT, DEF, TOSS, SHOVE, WARP, DASH, SPEED_UP, SLOW_DOWN}
enum STATUS_EFFECT {NONE, ALL, RANDOM, ACTED, SLEEP,}
enum DURATION_TYPE {NONE, TURN, ROUND}
#Passive Enums
enum PASSIVE_TYPE {NONE, VANTAGE, STAT_CHANGE, AURA, RESPONSE, FATED, SUB_WEAPON}

#Unit Enums
enum UNIT_ID {NONE, Remilia, Sakuya, Patchy, China,}
enum FACTION_ID {NONE, ENEMY, PLAYER, NPC,}
enum MOVE_TYPE {FOOT, FLY, RANGER,}
enum SPEC_ID {NONE, FAIRY,HUMAN,VAMPIRE,DRAGON,MAGICIAN,YOUKAI}
enum ACTION_TYPE {WEAPON, FRIENDLY_SKILL, HOSTILE_SKILL}
#, Human, Kappa, Lunarian, Oni, Doll, Devil, Yukionna, Zombie, Hermit, Magician, Spirit
enum JOB_ID {NONE, TRBLR, THIEF,}
enum WEP_ID {NONE, SPEAR, KNIFE,}
enum CORE_STAT {NONE, MOVE, LIFE, COMP, PWR, MAG, ELEG, CELE, BAR, CHA,}
enum ACTION_FAIL {NONE, DEAD, SLEEP, REACH, STRUCK}
enum WEAPON_CATEGORY {NONE, ANY, BLADE, BLUNT, STICK, BOW, GUN, GOHEI, BOOK, FAN, ACC, ITEM, KNIVES, NATURAL,}
#Combat Enums
enum COMP_TRIGGERS {NONE, ATTACK, WAS_HIT, MISS, DODGE, NEG_EFF, HEALED, MOVE, SKILL, CRIT, KILL, BREAK}
